name: Python Tests

on: [push, pull_request]

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        # python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        os: [ubuntu-latest]
        python-version: ['3.11']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -q PyPDF2 
        pip install -q "unstructured[all-docs]" pydantic
        if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
          apt-get install -y poppler-utils libmagic-dev tesseract-ocr libreoffice
        fi

    - name: Run tests
      run: |
        python -m unittest discover -s tests